### ISSUE TITLE
Add +/- to the Points

### ISSUE THREAD

**Issue by Miefmove** [modiholodri/GitHub-Actions#53]
You don't see if it's points going up or losing  in the +/- colom

**Comment by modiholodri** [comment]
You can see it, is just bad test data. So the top half is basically going up and the lower half going down... 
![Screenshot_20241021_214000_GitHub.jpg](https://github.com/user-attachments/assets/320c2402-0503-478a-a865-21ea2ee1ed5c)

**Comment by modiholodri** [comment]
Here I made you lose 10.2 points and it's shown as -10.2... 
![Screenshot_20241021_214627_GitHub.jpg](https://github.com/user-attachments/assets/f71c0c23-e59e-4eaf-bb40-211c75ad955f)

**Comment by modiholodri** [comment]
> You don't see if it's points going up or losing  in the +/- colom

Actually, good idea to write numbers with sign all the time like... 
-10.0
+7.3
+1.2
-4.7

**Comment by Miefmove** [comment]
Yes, I saw it later on when I went further down the list.
Still think adding a + for the positive change would make it clear immediately.

**Comment by modiholodri** [comment]
That's the difference from the last match...
