### ISSUE TITLE
Report actions

### ISSUE THREAD

**Issue by Miefmove** [modiholodri/GitHub-Actions#55]
I did reporting by issues and that works.
But at the beginning of your github actions it says report usual matches to actions and unusual to issues. I tried actions but can't  do anything there. 
Think best change info to report to issue only.

**Comment by modiholodri** [comment]
That's on the computer, but similar on the mobile (follow the yellow ones)...

![image](https://github.com/user-attachments/assets/c27e2493-0847-4f94-a971-6f6702d7f96a)

![image](https://github.com/user-attachments/assets/6c464cf1-3108-4236-bfeb-5082b500ed14)

**Comment by modiholodri** [comment]
That's how it looks on the mobile. The description needs improvement for sure... 

![Screenshot_20241022_094702_GitHub.jpg](https://github.com/user-attachments/assets/fb2d9377-1828-492c-8771-06cb700190a9)
